#!/applications/R/R-3.5.0/bin/Rscript

# Plot smoothed library-size-normalized coverage in windows along chromosomes

# Usage:
# csmit -m 100G -c 48 " Rscript ./DNAmethylation_chrProfiles.R BSseq_Rep8a_SRR6792678 1Mb 1000000"

#DNAmethName <- "BSseq_Rep8a_SRR6792679"
#winName <- "1Mb"
#winSize <- 1000000

args <- commandArgs(trailingOnly = T)
DNAmethName <- args[5]
winName <- args[7]
winSize <- as.numeric(args[8])

library(parallel)
library(GenomicRanges)

# Genomic definitions
chrs <- as.vector(read.table("/home/ajt200/analysis/wheat/sRNAseq_meiocyte_Martin_Moore/snakemake_sRNAseq/data/index/wheat_v1.0.fa.sizes")[,1])
#chrs <- chrs[-length(chrs)]
chrLens <- as.vector(read.table("/home/ajt200/analysis/wheat/sRNAseq_meiocyte_Martin_Moore/snakemake_sRNAseq/data/index/wheat_v1.0.fa.sizes")[,2])
#chrLens <- chrLens[-length(chrLens)]

if(grepl(pattern = "SRR67926", x = DNAmethName)) {
  DNAmethDir <- "/home/ajt200/analysis/wheat/epigenomics_shoot_leaf_IWGSC_2018_Science/BSseq/snakemake_BSseq/coverage/"
} else {
  stop(paste0("DNAmethName is not compatible with the specified coverage path"))
}

# Load processed DNA methylation data
mCG <- read.table(gzfile(paste0(DNAmethDir,
                                DNAmethName, "_MappedOn_wheat_v1.0_incl_organelles_controls_dedup_",
                                "CpG.gz.bismark.cov.gz")),
                  header = F, stringsAsFactors = F,
                  colClasses = c(rep(NA, 2), "NULL", NA, rep("NULL", 2)))
colnames(mCG) <- c("chr", "pos", "propMeth")
mCG$propMeth <- as.numeric(mCG$propMeth/100)
mCHG <- read.table(gzfile(paste0(DNAmethDir,
                                 DNAmethName, "_MappedOn_wheat_v1.0_incl_organelles_controls_dedup_",
                                 "CHG.gz.bismark.cov.gz")),
                   header = F, stringsAsFactors = F,
                   colClasses = c(rep(NA, 2), "NULL", NA, rep("NULL", 2)))
colnames(mCHG) <- c("chr", "pos", "propMeth")
mCHG$propMeth <- as.numeric(mCHG$propMeth/100)
mCHH <- read.table(gzfile(paste0(DNAmethDir,
                                 DNAmethName, "_MappedOn_wheat_v1.0_incl_organelles_controls_dedup_",
                                 "CHH.gz.bismark.cov.gz")),
                   header = F, stringsAsFactors = F,
                   colClasses = c(rep(NA, 2), "NULL", NA, rep("NULL", 2)))
colnames(mCHH) <- c("chr", "pos", "propMeth")
mCHH$propMeth <- as.numeric(mCHH$propMeth/100)

# Define windows as GRanges object
windowsGR <- GRanges()
for(i in 1:length(chrs)) {
  seqWindows <- seq(1, chrLens[i], by = winSize)
  windowsIR <- IRanges(start = seqWindows,
                       width = winSize)
  windowsIR <- windowsIR[-length(windowsIR)]
  windowsIR <- append(windowsIR,
                      IRanges(start = seqWindows[length(seqWindows)],
                              end = chrLens[i]))
  chrWindowsGR <- GRanges(seqnames = chrs[i],
                          ranges = windowsIR,
                          strand = "*")
  print(chrWindowsGR)
  windowsGR <- append(windowsGR, chrWindowsGR)
}

profileDNAmeth <- NULL
for(i in 1:length(chrs)) {
  print(chrs[i])
  chr_windowsGR <- windowsGR[seqnames(windowsGR) == chrs[i]]
  # mCG
  chr_mCG <- mCG[mCG$chr == chrs[i],]
  chr_mCG_GR <- GRanges(seqnames = chrs[i],
                        ranges = IRanges(start = chr_mCG$pos,
                                         width = 1),
                        strand = "*")
  # Identify overlapping windows and cytosine coordinates in CG context
  mCG_fOverlaps <- findOverlaps(query = chr_windowsGR,
                                subject = chr_mCG_GR,
                                type = "any",
                                select = "all",
                                ignore.strand = TRUE)
  # Convert mCG_fOverlaps into list object equivalent to that
  # generated by segmentSeq::getOverlaps(), in which each
  # list element corresponds to a genomic window of
  # sequentially numbered cytosine coordinates
  mCG_fOverlapsList <- mclapply(seq_along(unique(queryHits(mCG_fOverlaps))),
                       function(x) {
                         subjectHits(mCG_fOverlaps[queryHits(mCG_fOverlaps) == x])
                       }, mc.cores = detectCores(), mc.preschedule = T)  
  # Calculate mean methylation proportion in each window
  win_mCG <- sapply(mCG_fOverlapsList, function(x) {
               mean(chr_mCG$propMeth[x])
             })

  # mCHG
  chr_mCHG <- mCHG[mCHG$chr == chrs[i],]
  chr_mCHG_GR <- GRanges(seqnames = chrs[i],
                         ranges = IRanges(start = chr_mCHG$pos,
                                          width = 1),
                         strand = "*")
  # Identify overlapping windows and cytosine coordinates in CHG context
  mCHG_fOverlaps <- findOverlaps(query = chr_windowsGR,
                                 subject = chr_mCHG_GR,
                                 type = "any",
                                 select = "all",
                                 ignore.strand = TRUE)
  # Convert mCHG_fOverlaps into list object equivalent to that
  # generated by segmentSeq::getOverlaps(), in which each
  # list element corresponds to a genomic window of
  # sequentially numbered cytosine coordinates
  mCHG_fOverlapsList <- mclapply(seq_along(unique(queryHits(mCHG_fOverlaps))),
                        function(x) {
                          subjectHits(mCHG_fOverlaps[queryHits(mCHG_fOverlaps) == x])
                        }, mc.cores = detectCores(), mc.preschedule = T)  
  # Calculate mean methylation proportion in each window
  win_mCHG <- sapply(mCHG_fOverlapsList, function(x) {
                mean(chr_mCHG$propMeth[x])
              })

  # mCHH
  chr_mCHH <- mCHH[mCHH$chr == chrs[i],]
  chr_mCHH_GR <- GRanges(seqnames = chrs[i],
                         ranges = IRanges(start = chr_mCHH$pos,
                                          width = 1),
                         strand = "*")
  # Identify overlapping windows and cytosine coordinates in CHH context
  mCHH_fOverlaps <- findOverlaps(query = chr_windowsGR,
                                 subject = chr_mCHH_GR,
                                 type = "any",
                                 select = "all",
                                 ignore.strand = TRUE)
  # Convert mCHH_fOverlaps into list object equivalent to that
  # generated by segmentSeq::getOverlaps(), in which each
  # list element corresponds to a genomic window of
  # sequentially numbered cytosine coordinates
  mCHH_fOverlapsList <- mclapply(seq_along(unique(queryHits(mCHH_fOverlaps))),
                        function(x) {
                          subjectHits(mCHH_fOverlaps[queryHits(mCHH_fOverlaps) == x])
                        }, mc.cores = detectCores(), mc.preschedule = T)  
  # Calculate mean methylation proportion in each window
  win_mCHH <- sapply(mCHH_fOverlapsList, function(x) {
                mean(chr_mCHH$propMeth[x])
              })

  # Mean of all 3 contexts
  win_mC <- sapply(seq_along(win_mCG), function(x) {
              mean(c(win_mCG[x], win_mCHG[x], win_mCHH[x]))
            })

  # Make data.frame
  chr_profile <- data.frame(chr = chrs[i],
                            window = start(chr_windowsGR),
                            mCG = win_mCG,
                            mCHG = win_mCG,
                            mCHH = win_mCG,
                            mC = win_mCG,
                            stringsAsFactors = F)
  # Iteratively combine profiles from each chromosome
  # in a data.frame (profileDNAmeth) that grows with the
  # completion of each loop
  profileDNAmeth <- rbind(profileDNAmeth, chr_profile)
} 
write.table(profileDNAmeth,
            file = paste0(DNAmethName, "_per_", winName, ".txt"),
            sep = "\t", quote = F, row.names = F, col.names = T)
