THREADS: 32
MEMORY: "512g"
FILTER:
  cutadapt:
      R1_5prime_cut: 5 # -u
      R1_3prime_cut: -2 # -u
      R2_5prime_cut: 5 # -U
      R2_3prime_cut: -2 # -U
      adapter_R1: AGATCGGAAGAGCACACGTCTGAACTCCAGTCA # -a
      adapter_R2: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT # -A
      quality-filter: 20 # -q
      minimum-overlap: 3 # -O (default: 3)
      minimum-length: 30 # -m
      maximum-length: 76 # -M
      extra-params:
# NOTE: reference genome-specific mapping parameters
MAPPING:
      alignments: 4 # "In -k <N> mode, Bowtie 2 searches for up to N distinct, valid alignments for each read"
      reference: "data/index/wheat_v1.0"
      MAPQunique: 23 # -q
      MAPQmaxi: 2 # -q
      sortMemory: "10G"
COVERAGE:
      normalizeUsing: "CPM"
      ignoreForNormalization: "chrUn" # Reference genome-specific parameter
      binSize: 1
      genomeBinSize: 10000
      genomeBinName: "10kb"

# TruSeq adapters:
# http://emea.support.illumina.com/bulletins/2016/12/what-sequences-do-i-use-for-adapter-trimming.html
